// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase uygulamalarınızla kullanmak için varsayılan [FirebaseOptions].
///
/// Örnek:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else {
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          throw UnsupportedError(
            'DefaultFirebaseOptions henüz macOS için yapılandırılmadı - '
            'FlutterFire CLI yeniden çalıştırılarak yapılandırabilir.',
          );
        case TargetPlatform.windows:
          throw UnsupportedError(
            'DefaultFirebaseOptions henüz Windows için yapılandırılmadı - '
            'FlutterFire CLI yeniden çalıştırılarak yapılandırabilir.',
          );
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions henüz Linux için yapılandırılmadı - '
            'FlutterFire CLI yeniden çalıştırılarak yapılandırabilir.',
          );
        default:
          throw UnsupportedError(
            'Bu platform için DefaultFirebaseOptions desteklenmiyor.',
          );
      }
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW92f5NWITH19ZVAPSvEsbWVaqILXVHCg',
    appId: '1:496609829257:web:0e01282faa8ecaff10c158',
    messagingSenderId: '496609829257',
    projectId: 'fir-demo-2b844',
    authDomain: 'fir-demo-2b844.firebaseapp.com',
    storageBucket: 'fir-demo-2b844.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6Hq8nH6fOlYArK27kFv-97xuIDOpSNM',
    appId: '1:496609829257:android:d886573747978a7710c158',
    messagingSenderId: '496609829257',
    projectId: 'fir-demo-2b844',
    storageBucket: 'fir-demo-2b844.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUFEz_MNLdRy9rWaAGI2vliPavGN99mB4',
    appId: '1:496609829257:ios:2199a1ffbabe8aec10c158',
    messagingSenderId: '496609829257',
    projectId: 'fir-demo-2b844',
    storageBucket: 'fir-demo-2b844.appspot.com',
    iosClientId:
        '496609829257-728cqsv0l5nip85t1k59n01camqurdck.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTestcaseFlutter',
  );
}
